SELECT * FROM emp;
-- CREATE TABLE TABLE_NAME(COLUMN_NAME DATA_TYPE(LENGTH);

CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
SELECT * FROM emp_ddl;
DROP TABLE emp_ddl;
SELECT * FROM emp;
CREATE TABLE Dept_ddl AS SELECT * FROM dept;

SELECT * FROM dept_ddl;
CREATE TABLE salgrade_ddl AS SELECT * FROM salgrade;
SELECT * FROM SALGRADE_ddl;

/* ALTER TABLE TABLE_NAME
 * 1. ADD COLNAME DATETYPE;
 * 2. DROP COLNAME;
 * 3. MODIFY COLNAME DATATYPE;
 * 4. RENAME COLUMN OLD_COLNAME TO NEW_COLNAME
 * */

ALTER TABLE SALGRADE_DDL DROP COLUMN HOME;

RENAME SALGRADE_DDL TO SALZIP;

DESC SALZIP;
SELECT * FROM SALZIP;
TRUNCATE TABLE SALZIP;
DROP TABLE SALZIP;